# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:7.10
        
        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                key: v1-dependencies-{{ checksum "package.json" }}

            - run: 
                name: 'Instalando dependências do NPM'
                command: npm install

            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
                     
            - run: 
                name: 'Fazendo build do projeto'
                command: node_modules/gulp/bin/gulp.js build

            # - run: 
            #     name: 'Gerando artefato'
            #     command: cd build && tar cvfzp ~/repo/artifact.tgz *

            # - store_artifacts:
            #     path: ~/repo/artifact.tgz

            - run:
                name: 'Deploy via SSH'
                command: scp -o StrictHostKeyChecking=no -rv build/* $SSH:$INDEX_PATH
